<div class="team-member-block" data-sr="wait 0.5s, enter bottom">
    <div class="team-member-image">
        <a href="#">
            <?php if ($this->imageNode): ?>
                <img src="<?= $this->imageNode->getContent()->getUri() ?>" alt="<?= $this->fullname ?>" />
            <?php endif; ?>
        </a>

        <div class="team-member-overlay">
        </div>
    </div>

    <div class="team-member-caption">
        <h3>
            <a href="#">
                <?= $this->fullname ?>
            </a>
        </h3>

        <?= $this->position ?>
    </div>
</div>
