<?php
    /** @var \Nzxt\Model\Node $node */
    $node = $this->node;

    /** @var array $items */
    if ($this->type == 'services') {
        $items = $node->getChildren('', [\Application\Model\Content\Service::class]);
    } elseif ($this->type == 'members') {
        $items = $node->getChildren('', [\Application\Model\Content\Member::class]);
    }
?>
<div id="section-<?= $node->getID() ?>" class="section-page">
    <?php if ($this->type == 'normal'): ?>
        <?= $this->node->getRenderedChildren() ?>
    <?php else: ?>
        <div class="row">
            <div class="large-12 columns">
                <h2 class="section-title-block text-center title text-uppercase"><?= $this->headline ?></h2>
                <p class="lead"><?= $this->introduction ?></p>
            </div>
        </div>

        <div class="row">
            <?php foreach ($items as $index => $item): ?>
                <div class="medium-4 columns">
                    <?= $node->getRenderer()->render($item) ?>
                </div>

                <?php if (count($items) > 3 && ($index + 1) < count($items) && 0 == ($index + 1) % 3): ?>
                    <?php echo '</div><div class="row">' ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
