<div class="dialog-header">
    <div class="controls">
        <a class="toggle-panelsize" href="#" title="Change the size of this dialog.">
            <i class="fa fa-fw fa-arrows-h"></i>
        </a>

        <a class="toggle-help" href="#" title="Display information on several inputs.">
            <i class="fa fa-fw fa-question"></i>
        </a>

        <a class="dialog-close" href="#" title="Close this dialog.">
            <i class="fa fa-fw fa-times"></i>
        </a>
    </div>

    <h1><?= htmlspecialchars($this->title) ?></h1>
</div>
