<!DOCTYPE html>
<html class="no-js" lang="en" dir="ltr">
    <head>
        <?php if ($this->hasViewData('node')): ?>
            <title><?= htmlspecialchars($this->node->getTitle()) ?> | Nzxt cms</title>
        <?php else: ?>
            <title>Nzxt cms</title>
        <?php endif; ?>

        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Default Styles -->
        <link rel="stylesheet" href="/<?= $this->resourceDir ?>/vendor/font-awesome-4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="/<?= $this->resourceDir ?>/css/dialog.css">

        <script src="/<?= $this->resourceDir ?>/vendor/jquery/jquery.js"></script>
        <script src="/<?= $this->resourceDir ?>/vendor/jquery/jquery.easing.js"></script>
        <script src="/<?= $this->resourceDir ?>/vendor/trumbowyg-2.4.2/trumbowyg.min.js"></script>
        <script src="/<?= $this->resourceDir ?>/vendor/jquery.fileTree-1.01/jqueryFileTree.js"></script>
        <script src="/<?= $this->resourceDir ?>/vendor/jquery.ui-1.12.1/jquery-ui.js"></script>
        <script src="/<?= $this->resourceDir ?>/vendor/jquery.tooltip-1.3/jquery.tooltip.js"></script>
        <script src="/<?= $this->resourceDir ?>/js/dialog.js"></script>
    </head>

    <body class="cms typography">
        <?= $this->content ?>
    </body>
</html>
