<!DOCTYPE html>
<html class="no-js" lang="en" dir="ltr">
    <head>
        <title>Welcome to Nzxt cms</title>

        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Default Styles -->
        <link rel="stylesheet" href="/<?= $this->resourceDir ?>/vendor/ionicons-2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="/<?= $this->resourceDir ?>/vendor/font-awesome-4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="/<?= $this->resourceDir ?>/css/dialog.css">
        <link rel="stylesheet" href="/<?= $this->resourceDir ?>/css/login.css">

        <script src="/<?= $this->resourceDir ?>/vendor/jquery/jquery.js"></script>
        <script src="/<?= $this->resourceDir ?>/vendor/jquery.tooltip-1.3/jquery.tooltip.js"></script>
        <script src="/<?= $this->resourceDir ?>/js/dialog.js"></script>
    </head>

    <body class="cms typography accent-background">
        <?= $this->content ?>
    </body>
</html>
