<?php if ($this->user): ?>
    <?php
        $children = $this->node->getChildren();
    ?>

    <div class="typography folder-listing">
        <h1>Nodes in folder "<?= htmlspecialchars($this->node->getTitle()) ?>"</h1>

        <?php if (0 === count($children)): ?>
            <p>
                No nodes found in this folder.
            </p>
        <?php endif; ?>

        <?php if (1 === count($children)): ?>
            <p>
                1 node found in this folder. Click on the node to edit it.
            </p>
        <?php endif; ?>

        <?php if (1 < count($children)): ?>
            <p>
                <?= count($children) ?> nodes found in this folder. Click on a node to edit it.
            </p>
        <?php endif; ?>

        <?php foreach ($children as $child): ?>
            <?php
                $content = $child->getContent();
            ?>

            <div class="item">
                <i class="fa fa-fw <?= $child->getIcon() ?>"></i>

                <a href="<?= $this->linkBuilder->build('node:view', ['#node' => $child->getID() ]) ?>" class="cms">
                    <?= htmlspecialchars($child->getTitle()) ?>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
